name: ETL GoogleSheets → Postgres

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}
  schedule:
    - cron: "*/5 * * * *"  # every 5 minutes

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Connectivity check (Postgres)
        if: always()
        env:
            PGHOST: ${{ secrets.PGHOST }}
            PGPORT: ${{ secrets.PGPORT }}
            PGDATABASE: ${{ secrets.PGDATABASE }}
            PGUSER: ${{ secrets.PGUSER }}
            PGPASSWORD: ${{ secrets.PGPASSWORD }}
            PGSSLMODE: ${{ secrets.PGSSLMODE }}
        run: |
            sudo apt-get update -y && sudo apt-get install -y postgresql-client
            echo "Checking TCP reachability…"
            pg_isready -h "$PGHOST" -p "$PGPORT" -d "$PGDATABASE" || (echo "❌ Host/port unreachable"; exit 1)
            echo "Trying a simple SQL…"
            PGPASSWORD="$POSTGRES_PASSWORD" psql "host=$POSTGRES_HOST port=$POSTGRES_PORT dbname=$POSTGRES_DB user=$POSTGRES_USER sslmode=${PGSSLMODE:-require}" -c "select now();" -tA   

      - name: Run ETL
        env:
          PGHOST: ${{ secrets.POSTGRES_HOST }}
          PGPORT: ${{ secrets.POSTGRES_PORT }}
          PGDATABASE: ${{ secrets.POSTGRES_DB }}
          PGUSER: ${{ secrets.POSTGRES_USER }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          PGSSLMODE: ${{ secrets.PGSSLMODE }}
          GSERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_CRED }}
        run: |
          python read_gsheet.py
